#server.port=8001
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/productdb
#spring.datasource.username=root
#spring.datasource.password=getoffer
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8001

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/iproductdb
    username: root
    password: getoffer
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
